### ISSUE TITLE
Style guides with atomic design methodolgy

### ISSUE THREAD

**Issue by italomen** [modular-ui/modular-ui-directory#1]
Guias de estilo com a organização atômica:

Buffer style guide:
https://bufferapp.com/style-guide

Future Learn Library:
https://www.futurelearn.com/pattern-library

**Comment by tfvictorino** [comment]
Adicionei essa última aí também. 
Os exemplos de styleguides eu resolvi remover da lista pra não ficar muito extensa. Resolvi direcionar pro styleguides.io/examples.html, que serve esse propósito melhor :)
