### ISSUE TITLE
Include two suggested articles

### ISSUE THREAD

**Issue by italomen** [modular-ui/modular-ui-directory#6]
On Design Systems: Sell The Output, Not The Workflow - by Vitaly Friedman
https://www.smashingmagazine.com/2016/05/design-systems-responsive-design-sell-output-not-workflow/

Picking Parts, Products & People - by Nathan Curtis
A Team Activity to Start a Design System
https://medium.com/eightshapes-llc/picking-parts-products-people-a06721e81742#.ni1bl6mbn

**Comment by tfvictorino** [comment]
Thanks @italomen . Where do you think they fit best on the current topic structure?

**Comment by italomen** [comment]
The first one could be on "6) Styleguides and Pattern Libraries".

The last one fit in "2) About Components - General Concept".

**Comment by tfvictorino** [comment]
Added!
