### ISSUE TITLE
Include a few more resources about "Atomic CSS"

### ISSUE THREAD

**Issue by thierryk** [modular-ui/modular-ui-directory#7]
I'm thinking of:

   * [Challenging CSS Best Practices](http://www.smashingmagazine.com/2013/10/21/challenging-css-best-practices-atomic-approach/) on Smashing Magazine
   * http://acss.io (Atomic CSS powered by [Atomizer](https://github.com/acss-io/atomizer))
   * Atomic CSS [slide deck from FED London 2015](https://www.haikudeck.com/atomic-css-science-and-technology-presentation-dJ0xlFjhBQ)
   * [Atomic Cascading Style Sheets](https://www.youtube.com/watch?v=ojj_-6Xiud4) video from HTML5DevConf 2013

**Comment by tfvictorino** [comment]
Good point, @thierryk. Thanks for the suggestions!

I'll include the first two links into the `CSS Architecture` section. In a near future, we're thinking of expanding the `CSS Architecture/Methodologies` section to contemplate more references from each methodology. For now, the repo only list the existent ones with the main reference of each one. When this change is applied, we can go ahead and include the other two links. Does it make sense?

**Comment by thierryk** [comment]
@tfvictorino It makes sense, thanks.

**Comment by tfvictorino** [comment]
Cool! It's added on https://github.com/modular-ui/modular-ui-directory/commit/2a28d1769135b7dc45ddefb3733930184297645e. 😃
